| end file

	.globl __term0__LIB_LIST__
	.globl __term0__INIT_LIST__
	.globl __term0__EXIT_LIST__
	.globl __term0__CTOR_LIST__
	.globl __term0__DTOR_LIST__

.section	.list___LIB_LIST__,"aw"
__term0__LIB_LIST__:
		.long 0

.section	.list___INIT_LIST__,"aw"
__term0__INIT_LIST__:
		.long 0

.section	.list___EXIT_LIST__,"aw"
__term0__EXIT_LIST__:
		.long 0

.section	.list___CTOR_LIST__,"aw"
__term0__CTOR_LIST__:
		.long 0

.section	.list___DTOR_LIST__,"aw"
__term0__DTOR_LIST__:
		.long 0

